FROM rabbitmq:3.13-management

# Download matching stable delayed message exchange plugin
ADD https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez /plugins/

# Enable the plugin inside RabbitMQ
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange